services:
  api:
    build:
      context: ./apps/api
    ports:
      - "8000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/animerse
    depends_on:
      - db

  client:
    build:
      context: ./apps/client
    ports:
      - "5000:8080"
    depends_on:
      - api

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zforums
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: